services:
  db:
    image: mariadb:latest
    container_name: my_mariadb
    environment:
      MYSQL_ROOT_PASSWORD: platypus 
      MYSQL_DATABASE: laundry_management
      MYSQL_USER: perry
      MYSQL_PASSWORD: the
    ports:
      - "3353:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

volumes:
  db_data:

