services:
  mysql:
    image: mysql:latest
    container_name: mysql_db 
    environment:
      MYSQL_ROOT_PASSWORD: sexy  # Set your root password here
      MYSQL_DATABASE: laundry_management  # Set your database name here
      MYSQL_USER: nikhil  # Optional: Create a user for the database
      MYSQL_PASSWORD: goat  # Optional: Set the user's password
    volumes:
      - ./db_data:/var/lib/mysql  # Persist data in this folder
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Initialize the DB with your script
    ports:
      - "3354:3306"  # Expose MySQL port for connections

volumes:
  db_data:

